CREATE OR REPLACE VIEW VWTOTALES AS
SELECT UNIQUE 
( SELECT COUNT(*) FROM COOPESOCIOS) AS COOPESOCIOS,
( SELECT COUNT(*) FROM MAESTROCLIENTESSALDOS) AS MAESTROCLIENTESSALDOS,
( SELECT COUNT(*) FROM MOVIMIENTOS) AS MOVIMIENTOS,
( SELECT COUNT(*) FROM MAESTROPRESTAMOS) AS MAESTROPRESTAMOS,
( SELECT COUNT(*) FROM PLANPAGOS) AS PLANPAGOS,
( SELECT COUNT(*) FROM CERTIFICADOS) AS CERTIFICADOS,
( SELECT COUNT(*) FROM GARANTES) AS GARANTES,
( SELECT COUNT(*) FROM GARANTESDETALLE) AS GARANTESDETALLE,
( SELECT COUNT(*) FROM GARANTIZADOS) AS GARANTIZADOS,
( SELECT COUNT(*) FROM FRA) AS FRA,
( SELECT COUNT(*) FROM SINIESTROS) AS SINIESTROS,
( SELECT COUNT(*) FROM VIDEOS) AS VIDEOS
FROM COOPESOCIOS c;

CREATE OR REPLACE VIEW VWTOTALES2 AS
SELECT UNIQUE 'COOPESOCIOS' AS NOMBRE, (SELECT COUNT(*) FROM COOPESOCIOS) AS TOTAL
FROM COOPESOCIOS
UNION
SELECT UNIQUE 'MAESTROCLIENTESSALDOS' AS NOMBRE, (SELECT COUNT(*) FROM MAESTROCLIENTESSALDOS) AS TOTAL
FROM MAESTROCLIENTESSALDOS 
UNION
SELECT UNIQUE 'MOVIMIENTOS' AS NOMBRE, (SELECT COUNT(*) FROM MOVIMIENTOS) AS TOTAL
FROM MOVIMIENTOS
UNION
SELECT UNIQUE 'MAESTROPRESTAMOS' AS NOMBRE, (SELECT COUNT(*) FROM MAESTROPRESTAMOS) AS TOTAL
FROM MAESTROPRESTAMOS
UNION
SELECT UNIQUE 'PLANPAGOS' AS NOMBRE, (SELECT COUNT(*) FROM PLANPAGOS) AS TOTAL
FROM PLANPAGOS
UNION
SELECT UNIQUE 'CERTIFICADOS' AS NOMBRE, (SELECT COUNT(*) FROM CERTIFICADOS) AS TOTAL
FROM CERTIFICADOS
UNION
SELECT UNIQUE 'GARANTES' AS NOMBRE, (SELECT COUNT(*) FROM GARANTES) AS TOTAL
FROM GARANTES
UNION
SELECT UNIQUE 'GARANTESDETALLE' AS NOMBRE, (SELECT COUNT(*) FROM GARANTESDETALLE) AS TOTAL
FROM GARANTESDETALLE
UNION
SELECT UNIQUE 'GARANTIZADOS' AS NOMBRE, (SELECT COUNT(*) FROM GARANTIZADOS) AS TOTAL
FROM GARANTIZADOS
UNION
SELECT UNIQUE 'FRA' AS NOMBRE, (SELECT COUNT(*) FROM FRA) AS TOTAL
FROM FRA
UNION
SELECT UNIQUE 'SINIESTROS' AS NOMBRE, (SELECT COUNT(*) FROM SINIESTROS) AS TOTAL
FROM SINIESTROS
UNION
SELECT UNIQUE 'VIDEOS' AS NOMBRE, (SELECT COUNT(*) FROM VIDEOS) AS TOTAL
FROM VIDEOS;
