-- Table and views related to socios

CREATE TABLE CoopeSocios 
	( CodEmpleado CHAR(15) NOT NULL COMPRESS SYSTEM DEFAULT,
	  CodPais CHAR(5) NOT NULL COMPRESS SYSTEM DEFAULT,
	  NombreEmpleado CHAR(70) NOT NULL COMPRESS SYSTEM DEFAULT,
	  emailEmpleado CHAR(70) COMPRESS SYSTEM DEFAULT,
	  company CHARACTER(10) COMPRESS SYSTEM DEFAULT,
	  inBluePages BOOLEAN ,
	  Activo BOOLEAN ,
	  isAdmin BOOLEAN DEFAULT FALSE,
	  uuid CHAR(40) NOT NULL COMPRESS SYSTEM DEFAULT,

	  FecModificacion TIMESTAMP(12) DEFAULT CURRENT_TIMESTAMP,
	  PRIMARY KEY(CodEmpleado)
	  ) 
	  VALUE COMPRESSION COMPRESS YES;

CREATE TABLE COOPESOCIOSTEMP LIKE COOPESOCIOS;

CREATE VIEW vwCoopeAdmins AS
SELECT *
FROM CoopeSocios
WHERE isAdmin = TRUE;

CREATE VIEW vwSociosExEmpleados AS
SELECT *
FROM CoopeSocios
WHERE inBluePages = FALSE AND Activo = TRUE;

CREATE VIEW vwSociosIBM AS
SELECT *
FROM CoopeSocios
WHERE inBluePages = TRUE AND Activo = TRUE AND Company = 'IBM';

CREATE VIEW vwSociosKYNDRYL AS
SELECT *
FROM CoopeSocios
WHERE inBluePages = TRUE AND Activo = TRUE AND Company = 'KYNDRYL';

CREATE VIEW vwSociosActivos AS
SELECT CODEMPLEADO, CODPAIS, NOMBREEMPLEADO, LOWER(EMAILEMPLEADO) EMAILEMPLEADO, COMPANY, INBLUEPAGES, ACTIVO, ISADMIN, FECMODIFICACION, UUID  
FROM CoopeSocios
WHERE Activo = TRUE;

CREATE VIEW vwSociosInactivos AS
SELECT CODEMPLEADO, CODPAIS, NOMBREEMPLEADO, LOWER(EMAILEMPLEADO) EMAILEMPLEADO, COMPANY, INBLUEPAGES, ACTIVO, ISADMIN, FECMODIFICACION, UUID 
FROM CoopeSocios
WHERE Activo = FALSE;

CREATE INDEX idxEmails
ON COOPESOCIOS(emailEmpleado)
COMPRESS YES;

CREATE UNIQUE INDEX idxSociosUuid
ON COOPESOCIOS(uuid)
COMPRESS YES;

CREATE INDEX idxSociosCompany
ON COOPESOCIOS(company)
COMPRESS YES;
