CREATE OR REPLACE VIEW VWSociosDetalle AS
SELECT UNIQUE CS.CODEMPLEADO, CS.NOMBREEMPLEADO, CS.EMAILEMPLEADO, MC.DIRECCIONEMPLEADO, CS.UUID 
FROM  COOPESOCIOS CS
LEFT JOIN MAESTROCLIENTESSALDOS MC
ON MC.CODEMPLEADO = CS.CODEMPLEADO;

CREATE OR REPLACE VIEW CERTIFICADOSSOLES AS 
SELECT *
FROM CERTIFICADOS
WHERE TIPOCERT = '01';

CREATE OR REPLACE VIEW CERTIFICADOSUSD AS 
SELECT *
FROM CERTIFICADOS
WHERE TIPOCERT = '02';

CREATE OR REPLACE VIEW CTSSOLES AS 
SELECT *
FROM CERTIFICADOS
WHERE TIPOCERT = '03';

CREATE OR REPLACE VIEW CTSUSD AS 
SELECT *
FROM CERTIFICADOS
WHERE TIPOCERT = '04';

CREATE OR REPLACE VIEW CERTIFICADOSSOLESMONTOS AS
SELECT TipoId, TipoCert, CodEmpleado, CtaCliente,
        NumDoc, Vers, Plazo, TipoPago,
		Monto, InteresP, InteresC, Interes, 
		ROUND(InteresC + InteresP, 2) INTERESG,
		ROUND(monto + InteresC + InteresP, 2) VALOR,
		FecEmision, FecVencimiento		
FROM CERTIFICADOSSOLES;

CREATE OR REPLACE VIEW CERTIFICADOSSOLESMONTOSTOTALES AS
SELECT TipoCert, CodEmpleado, CtaCliente, TipoPago, 
		ROUND(SUM(Monto), 2) TOTALMONTOS, ROUND(SUM(InteresP), 2) TOTALINTERESP, 
        ROUND(SUM(InteresC), 2) TOTALINTERESC, ROUND(SUM(Interes), 2) TOTALINTERES,
		ROUND(SUM(Valor), 2) TOTALVALOR
FROM CERTIFICADOSSOLESMONTOS
GROUP BY TIPOCERT, CODEMPLEADO, CTACLIENTE, TIPOPAGO;

CREATE OR REPLACE VIEW CERTIFICADOSUSDMONTOS AS
SELECT TipoId, TipoCert, CodEmpleado, CtaCliente,
        NumDoc, Vers, Plazo, TipoPago,
		Monto, InteresP, InteresC, Interes, 
		ROUND(InteresC + InteresP, 2) INTERESG,
		ROUND(monto + InteresC + InteresP, 2) VALOR,
		FecEmision, FecVencimiento		
FROM CERTIFICADOSUSD;

CREATE OR REPLACE VIEW CERTIFICADOSUSDMONTOSTOTALES AS
SELECT TipoCert, CodEmpleado, CtaCliente, TipoPago, 
		ROUND(SUM(Monto), 2) TOTALMONTOS, ROUND(SUM(InteresP), 2) TOTALINTERESP, 
        ROUND(SUM(InteresC), 2) TOTALINTERESC, ROUND(SUM(Interes), 2) TOTALINTERES,
		ROUND(SUM(Valor), 2) TOTALVALOR
FROM CERTIFICADOSUSDMONTOS
GROUP BY TIPOCERT, CODEMPLEADO, CTACLIENTE, TIPOPAGO;

CREATE OR REPLACE VIEW CTSSOLESMONTOS AS
SELECT TipoId, TipoCert, CodEmpleado, CtaCliente,
        NumDoc, Vers, Plazo, TipoPago,
		Monto, InteresP, InteresC, Interes, 
		ROUND(InteresC + InteresP, 2) INTERESG,
		ROUND(monto + InteresC + InteresP, 2) VALOR,
		FecEmision, FecVencimiento		
FROM CTSSOLES;

CREATE OR REPLACE VIEW CTSSOLESMONTOSTOTALES AS
SELECT TipoCert, CodEmpleado, CtaCliente, TipoPago, 
		ROUND(SUM(Monto), 2) TOTALMONTOS, ROUND(SUM(InteresP), 2) TOTALINTERESP, 
        ROUND(SUM(InteresC), 2) TOTALINTERESC, ROUND(SUM(Interes), 2) TOTALINTERES,
		ROUND(SUM(Valor), 2) TOTALVALOR
FROM CTSSOLESMONTOS
GROUP BY TIPOCERT, CODEMPLEADO, CTACLIENTE, TIPOPAGO;

CREATE OR REPLACE VIEW CTSUSDMONTOS AS
SELECT TipoId, TipoCert, CodEmpleado, CtaCliente,
        NumDoc, Vers, Plazo, TipoPago,
		Monto, InteresP, InteresC, Interes, 
		ROUND(InteresC + InteresP, 2) INTERESG,
		ROUND(monto + InteresC + InteresP, 2) VALOR,
		FecEmision, FecVencimiento		
FROM CTSUSD;

CREATE OR REPLACE VIEW CTSUSDMONTOSTOTALES AS
SELECT TipoCert, CodEmpleado, CtaCliente, TipoPago, 
		ROUND(SUM(Monto), 2) TOTALMONTOS, ROUND(SUM(InteresP), 2) TOTALINTERESP, 
        ROUND(SUM(InteresC), 2) TOTALINTERESC, ROUND(SUM(Interes), 2) TOTALINTERES,
		ROUND(SUM(Valor), 2) TOTALVALOR
FROM CTSUSDMONTOS
GROUP BY TIPOCERT, CODEMPLEADO, CTACLIENTE, TIPOPAGO;

CREATE OR REPLACE VIEW PRSOLAFIRMA AS
SELECT M.*
FROM MAESTROPRESTAMOS M
WHERE IDMOVIMIENTO = '0201';

CREATE OR REPLACE VIEW PRCORTOPLAZO AS
SELECT M.*
FROM MAESTROPRESTAMOS M
WHERE IDMOVIMIENTO = '0202';

CREATE OR REPLACE VIEW PRACADEMICO AS
SELECT M.*
FROM MAESTROPRESTAMOS M
WHERE IDMOVIMIENTO = '0203';

CREATE OR REPLACE VIEW PRLARGOPLAZO AS
SELECT M.*
FROM MAESTROPRESTAMOS M
WHERE IDMOVIMIENTO = '0204';

CREATE OR REPLACE VIEW PRHIPOTECARIO AS
SELECT M.*
FROM MAESTROPRESTAMOS M
WHERE IDMOVIMIENTO = '0205';

CREATE OR REPLACE VIEW PRCONSUMO AS
SELECT M.*
FROM MAESTROPRESTAMOS M
WHERE IDMOVIMIENTO = '0206';

CREATE OR REPLACE VIEW PRAUTOMOVIL AS
SELECT M.*
FROM MAESTROPRESTAMOS M
WHERE IDMOVIMIENTO = '0207';

CREATE OR REPLACE VIEW PRPS AS
SELECT M.*
FROM MAESTROPRESTAMOS M
WHERE IDMOVIMIENTO = '0208';

CREATE OR REPLACE VIEW PRESP1 AS
SELECT M.*
FROM MAESTROPRESTAMOS M
WHERE IDMOVIMIENTO = '0209';

CREATE OR REPLACE VIEW PRESP2 AS
SELECT M.*
FROM MAESTROPRESTAMOS M
WHERE IDMOVIMIENTO = '0210';

CREATE OR REPLACE VIEW VWMASTERPLANPAGOS AS
SELECT 
	tot.NUMOPERACION, tot.IDMOVIMIENTO,
	tot.TOTALMONTOS, tot.TOTALINTERES, tot.TOTALINTERESMORATORIO, tot.TOTALCUOTAS,
	pend.TOTALMONTOS PENDTOTALMONTOS, pend.TOTALINTERES PENDTOTALINTERES,
	pend.TOTALINTERESMORATORIO PENDTOTALINTERESMORATORIO, pend.TOTALCUOTAS PENDTOTALCUOTAS,
	canc.TOTALMONTOS CANTOTALMONTOS, canc.TOTALINTERES CANTOTALINTERES,
	canc.TOTALINTERESMORATORIO CANTOTALINTERESMORATORIO, canc.TOTALCUOTAS CANTOTALCUOTAS
FROM 
	PLANPAGOSTOTALES tot
LEFT JOIN PLANPAGOSTOTALPENDIENTES pend
ON
	tot.NUMOPERACION = pend.NUMOPERACION AND 
	tot.IDMOVIMIENTO = pend.IDMOVIMIENTO 
LEFT JOIN PLANPAGOSTOTALCANCELADOS canc
ON
	tot.NUMOPERACION = canc.NUMOPERACION AND 
	tot.IDMOVIMIENTO = canc.IDMOVIMIENTO;

CREATE OR REPLACE VIEW VWMASTERLOOKUP AS
SELECT 
	cs.UUID, cs.EMAILEMPLEADO , cs.CODEMPLEADO, cs.CODPAIS, cs.COMPANY, cs.NOMBREEMPLEADO,  
	cs.INBLUEPAGES, cs.ACTIVO, cs.ISADMIN,
	det.DIRECCIONEMPLEADO,
	ctas.ctasoles, ctas.CTAUSD,
	ctasdet.SALDOCONTABLESOL, ctasdet.SALDOCONTABLEUSD, ctasdet.SALDODISPAHORROSOL, ctasdet.SALDODISPAHORROUSD,
	ctasdet.SALDOBLOQUEOAHORROSOL, ctasdet.SALDOBLOQUEOAHORROUSD, ctasdet.INTAHORROMESSOL, ctasdet.INTAHORROMESUSD,
	ctasdet.SALDOAPORTACIONSOL, ctasdet.SALDOAPORTACIONUSD, ctasdet.SALDOMISCELANEOSOL, ctasdet.SALDOMISCELANEOUSD,
	ctasdet.INTMISCELANEOMESSOL, ctasdet.INTMISCELANEOMESUSD,
	certmontos.CERTSOLVALOR, certmontos.CERTSOLMONTOS, certmontos.CERTUSDVALOR, certmontos.CERTUSDMONTOS,
    certmontos.CTSSOLVALOR, certmontos.CTSSOLMONTOS, certmontos.CTSUSDVALOR, certmontos.CTSUSDMONTOS,
    ctassaldos.SOLSALDOPRESSOLAFIRMA, ctassaldos.SOLSALDOPRESCONSUMO, 
    ctassaldos.SOLSALDOPRESCORTOPLAZO, ctassaldos.SOLSALDOPRESMEDIANOPLAZO, ctassaldos.SOLSALDOPRESLARGOPLAZO,
	ctassaldos.SOLSALDOPRESHIPOTECARIO, ctassaldos.SOLSALDOPRESAUTO,
	ctassaldos.SOLSALDOPRESPS1, ctassaldos.SOLSALDOPRESESP1, ctassaldos.SOLSALDOPRESESP2,
	ctassaldos.USDSALDOPRESSOLAFIRMA, ctassaldos.USDSALDOPRESCONSUMO,
	ctassaldos.USDSALDOPRESCORTOPLAZO, ctassaldos.USDSALDOPRESMEDIANOPLAZO, ctassaldos.USDSALDOPRESLARGOPLAZO,
	ctassaldos.USDSALDOPRESHIPOTECARIO, ctassaldos.USDSALDOPRESAUTO,
	ctassaldos.USDSALDOPRESPS1, ctassaldos.USDSALDOPRESESP1, ctassaldos.USDSALDOPRESESP2
FROM CoopeSocios cs
LEFT JOIN VWSOCIOSDETALLE det
ON
	cs.UUID = det.UUID 
LEFT JOIN CTASEMPLEADO ctas
ON
	cs.CODEMPLEADO = ctas.CODEMPLEADO 
LEFT JOIN CUENTASDETALLES ctasdet
ON
	cs.UUID = ctasdet.UUID
LEFT JOIN CERTIFICADOSMONTOSTOTALESID certmontos
ON
	cs.UUID = certmontos.UUID
LEFT JOIN CUENTASSALDOS ctassaldos
ON
	cs.UUID = ctassaldos.UUID;
