CREATE TABLE UsersLogin 
	( emailEmpleado CHAR(70) NOT NULL COMPRESS SYSTEM DEFAULT,
	  FecLogin TIMESTAMP(12) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	  PRIMARY KEY(emailEmpleado, FecLogin)
	  ) 
	  VALUE COMPRESSION COMPRESS YES;

CREATE INDEX idxLoginEmail
ON USERSLOGIN(emailEmpleado)
COMPRESS YES;

CREATE INDEX idxLoginFecha
ON USERSLOGIN(FecLogin)
COMPRESS YES;

CREATE VIEW LOGINUSERS AS
SELECT DATE(FECLOGIN) FECHA, COUNT(*) CANTIDAD
FROM USERSLOGIN
GROUP BY DATE(FECLOGIN);
