ALTER TABLE COOPESOCIOS ADD EMAILEMPLEADO2 VARCHAR(70);

DROP TABLE COOPESOCIOSTEMP;

CREATE TABLE IF NOT EXISTS COOPESOCIOSTEMP LIKE COOPESOCIOS;

CREATE OR REPLACE VIEW vwSociosActivos AS
SELECT CODEMPLEADO, NOMBREEMPLEADO, LOWER(EMAILEMPLEADO) EMAILEMPLEADO, LOWER(EMAILEMPLEADO2) EMAILEMPLEADO2, UUID  
FROM CoopeSocios
WHERE Activo = TRUE;

CREATE OR REPLACE VIEW vwSociosInactivos AS
SELECT CODEMPLEADO, NOMBREEMPLEADO, LOWER(EMAILEMPLEADO) EMAILEMPLEADO, LOWER(EMAILEMPLEADO2) EMAILEMPLEADO2, UUID 
FROM CoopeSocios
WHERE Activo = FALSE;
