name: Cooperativa web dataapi
on:
  pull_request_target:
    types: [opened, synchronize, closed]
    branches:    
      - 'master'
    paths:
      - 'web/dataapi/**'
env:
  working-directory: ./web/dataapi
jobs:
  prepare:
    runs-on: ubuntu-latest
    environment: UAT
    steps:
    - name: Update OS
      run: |
        sudo apt-get update && sudo apt-get upgrade
        sudo apt autoremove
    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: '16.14.2'
    - name : Update npm
      run: |
        npm install npm@latest -g
        node -v
        npm -version
    - name: Install loopback
      run: npm install -g @loopback/cli
  install:
    needs: [prepare]
    runs-on: ubuntu-latest
    environment: UAT
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name : Update npm
      run: |
        npm install npm@latest -g
        node -v
        npm -version
    - name: Install packages
      run: |
        npm install
        npm prune
      working-directory: ${{env.working-directory}}
    - name : Prepare env file
      run: |
        cp ./src/datasources/env.ts.template ./src/datasources/env.ts
        sed -i 's/<CLOUDANT.DB>/${{secrets.CLOUDANT_DB}}/' ./src/datasources/env.ts
        sed -i 's/<CLOUDANT.MODEL>/${{secrets.CLOUDANT_MODEL}}/' ./src/datasources/env.ts
        sed -i 's/<CLOUDANT.PASSWORD>/${{secrets.CLOUDANT_PWD}}/' ./src/datasources/env.ts
        sed -i 's/<CLOUDANT.URL>/${{secrets.CLOUDANT_URL}}/' ./src/datasources/env.ts
        sed -i 's/<CLOUDANT.USERNAME>/${{secrets.CLOUDANT_USER}}/' ./src/datasources/env.ts
        cat ./src/datasources/env.ts
      working-directory: ${{env.working-directory}} 
  build:
    needs: [install]
    runs-on: ubuntu-latest
    environment: UAT
    steps:
    - run: echo Building web dataapi
  deploy:
    needs: [build]
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: UAT
    steps:
    - run: echo Deploying web-dataapi