name: Cooperativa web dataapi PR
on:
  pull_request_target:
    types: [opened, synchronize, closed]
    branches:    
      - 'master'
    paths:
      - 'web/dataapi/**'
jobs:
  PR-Web-dataapi:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was created/updated for web dataapi
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged for web-dataapi