name: Cooperativa web dataapi
on:
  pull_request_target:
    types: [opened, synchronize, closed]
    branches:    
      - 'master'
    paths:
      - 'web/dataapi/**'
jobs:
  prepare:
    runs-on: ubuntu-latest
    environment: UAT
    steps:
    - name: Update OS
      run: sudo apt-get update && sudo apt-get upgrade
    - name: Clean OS libs
      run: sudo apt autoremove
    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: '16.14.2'
    - name : Update npm
      run: npm install npm@latest -g
    - name: Verify node & npm versions
      run: node -v && npm -version
    - name: Install loopback
      run: npm install -g @loopback/cli
  install:
    needs: [prepare]
    runs-on: ubuntu-latest
    environment: UAT
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: change folder
      run: cd web/dataapi && pwd
    - name: Install packages
      run: pwd && npm install && npm prune
    - name: Run init script
      run: cd scripts && node init.js && cd ..
    - name: Show env file
      run: cat src/datasources/env.ts
  build:
    needs: [install]
    runs-on: ubuntu-latest
    environment: UAT
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - run: echo The PR was created/updated for web dataapi
  deploy:
    needs: [build]
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: UAT
    steps:
    - run: echo The PR was merged for web-dataapi