name: Cooperativa web dataapi
on:
  pull_request_target:
    types: [opened, synchronize, closed]
    branches:    
      - 'master'
    paths:
      - 'web/dataapi/**'
env:
  working-directory: ./web/dataapi
jobs:
  prepare:
    runs-on: ubuntu-latest
    environment: UAT
    steps:
    - name: Update OS
      run: |
        sudo apt-get update && sudo apt-get upgrade
        sudo apt autoremove
    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: '16.14.2'
    - name : Update npm
      run: |
        npm install npm@latest -g
        node -v
        npm -version
    - name: Install loopback
      run: npm install -g @loopback/cli
  install:
    needs: [prepare]
    runs-on: ubuntu-latest
    environment: UAT
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install packages
      run: |
        npm install
        npm prune
      working-directory: ${{env.working-directory}}
    - name: Run init script
      run: |
        cd scripts
        node init.js
      working-directory: ${{env.working-directory}}
    - name: Show env file
      run: cat ./src/datasources/env.ts
      working-directory: ${{env.working-directory}}
  build:
    needs: [install]
    runs-on: ubuntu-latest
    environment: UAT
    steps:
    - run: echo Building web dataapi
  deploy:
    needs: [build]
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: UAT
    steps:
    - run: echo Deploying web-dataapi